import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const VALID_TENANTS = ["acme", "globex", "skylogix"];

function getTenantFromHost(host: string): string | null {
  const subdomain = host.split(".")[0];
  if (VALID_TENANTS.includes(subdomain)) {
    return subdomain;
  }
  return null;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const cookieStore = await cookies();

  const host = headersList.get("host") ?? "";
  const tenantFromSubdomain = getTenantFromHost(host);
  const tenantFromCookie = cookieStore.get("tenant")?.value;

  // Priority: subdomain > cookie
  const tenantId = tenantFromSubdomain ?? tenantFromCookie;

  return (
    <html lang="en">
      <head>
        {tenantId && (
          <link
            rel="stylesheet"
            href={`/api/themes/${tenantId}`}
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
