name: Cleanup Preview
on:
  pull_request:
    types: [closed]

jobs:
  delete-neon-branch:
    if: vars.NEON_PROJECT_ID != ''
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
